作業目標<br>
計算有缺失值的資料，統計量實作<br>
作業重點<br>
當遇到缺失值有函式可以處理，不須額外寫程式刪除<br>
計算統計量時不能出現缺失值

題目:<br>
english_score = np.array([55,89,76,65,48,70])<br>
math_score = np.array([60,85,60,68,np.nan,60])<br>
chinese_score = np.array([65,90,82,72,66,77])<br>
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。<br>
1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
3. 用補考後資料找出與國文成績相關係數最高的學科?

In [6]:
import numpy as np

In [9]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [14]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
english_average = np.average(english_score)
math_average = np.nanmean((math_score))
chinese_average = np.average(chinese_score)

print(f'英文科平均成績 = {english_average}; 數學科平均成績 = {math_average}; 國文科平均成績 = {chinese_average}')

english_max = np.nanmax(english_score)
math_max  = np.nanmax(math_score)
chinese_max  = np.nanmax(chinese_score)

print(f'英文科最大值 = {english_max}; 數學科最大值 = {math_max}; 國文科最大值 = {chinese_max}')

english_min = np.nanmin(english_score)
math_min  = np.nanmin(math_score)
chinese_min  = np.nanmin(chinese_score)

print(f'英文科最小值 = {english_min}; 數學科最小值 = {math_min}; 國文科最小值 = {chinese_min}')

english_std = np.nanstd(english_score)
math_std  = np.nanstd(math_score)
chinese_std  = np.nanstd(chinese_score)

print(f'英文科標準差 = {english_std}; 數學科標準差 = {math_std}; 國文科標準差 = {chinese_std}')


英文科平均成績 = 67.16666666666667; 數學科平均成績 = 66.6; 國文科平均成績 = 75.33333333333333
英文科最大值 = 89; 數學科最大值 = 85.0; 國文科最大值 = 90
英文科最小值 = 48; 數學科最小值 = 60.0; 國文科最小值 = 65
英文科標準差 = 13.433995020924426; 數學科標準差 = 9.707728879609279; 國文科標準差 = 8.825468196582484


In [17]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
math_score[4] = 55
math_average = np.nanmean((math_score))
math_max  = np.nanmax(math_score)
math_min  = np.nanmin(math_score)
math_std  = np.nanstd(math_score)

print(f'數學科平均成績 = {math_average}; 數學科最大值 = {math_max}; 數學科最大值 = {math_min}; 數學科標準差 = {math_std}')

數學科平均成績 = 64.66666666666667; 數學科最大值 = 85.0; 數學科最大值 = 55.0; 數學科標準差 = 9.860132971832694


In [24]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?
#補考後資料國文與數學成績相關係數
corrcoef_chinese_math= np.corrcoef(chinese_score, math_score)
corrcoef_chinese_math

array([[1.        , 0.74056803],
       [0.74056803, 1.        ]])

In [25]:
#補考後資料國文與英文成績相關係數
np.corrcoef(chinese_score, english_score)

array([[1.        , 0.97792828],
       [0.97792828, 1.        ]])

In [26]:
#故補考後資料國文成績相關係數最高的學科為英文
np.fmax(corrcoef_chinese_math, corrcoef_chinese_english)

array([[1.        , 0.97792828],
       [0.97792828, 1.        ]])